apiversion: apps/v
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replica: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
        
    